name: RateAddon
version: ${project.version}
main: net.d3jott.rateaddon.RateAddon
authors: [D3joTT]
api-version: 1.13
depend: ["PlotSquared", "PlaceholderAPI"]
commands:
  top:
    description: Top plots
    usage: /top
    aliases: [topka, topserca, topserduszka, serduszkatop, sercatop]
  serce:
    description: Give heart
    usage: /serce
    aliases: [serduszko, serca, serduszka, ciastko, ciasteczko, heart, cookie]
